theme: jekyll-theme-minimal
<table border="1" class="dataframe">
	<thead>
	  <tr style="text-align: right;">
		<th>projname</th>
		<th>تست</th>
		<th>تندگویان - آفگس</th>
		<th>تندگویان - بلودان</th>
		<th>دره زار - خط انتقال</th>
		<th>صبا فولاد- خط انتقال</th>
		<th>وندورهای تامین کالا</th>
		<th>گل گهر - جابجايي خط</th>
		<th>گل گهر- تیکنر مرکزی</th>
	  </tr>
	  <tr>
		<th>fullname</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	  </tr>
	</thead>
	<tbody>
	  <tr>
		<th></th>
		<td>1.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>ابوطالب طالبی</th>
		<td></td>
		<td></td>
		<td></td>
		<td>195.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>امیر کریمی</th>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>28.0</td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>تقی رحیمیان</th>
		<td>5.0</td>
		<td></td>
		<td></td>
		<td>28.0</td>
		<td></td>
		<td>33.0</td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>جعفر ذولفقاری</th>
		<td></td>
		<td></td>
		<td></td>
		<td>7.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>حسین سام</th>
		<td></td>
		<td></td>
		<td></td>
		<td>169.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>داریوش بابادی</th>
		<td></td>
		<td></td>
		<td></td>
		<td>162.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>سامان شاه محمدی</th>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>6.0</td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>سعید بیژنی</th>
		<td></td>
		<td></td>
		<td>6.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>عباس عباس آبادی</th>
		<td></td>
		<td></td>
		<td></td>
		<td>1.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>علی مولایی ارپناهی</th>
		<td></td>
		<td></td>
		<td></td>
		<td>198.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>فرزانه پناهیان</th>
		<td></td>
		<td>6.0</td>
		<td>171.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>فرهاد گنجیان</th>
		<td></td>
		<td></td>
		<td></td>
		<td>3.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>فرید ویسی</th>
		<td></td>
		<td></td>
		<td></td>
		<td>702.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>محسن صحراییان</th>
		<td>10.0</td>
		<td></td>
		<td></td>
		<td>1.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>محمد امینی</th>
		<td></td>
		<td></td>
		<td></td>
		<td>171.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	  <tr>
		<th>مصطفی امیدعلی</th>
		<td>1.0</td>
		<td>2.0</td>
		<td>36.0</td>
		<td>47.0</td>
		<td>50.0</td>
		<td></td>
		<td>27.0</td>
		<td>50.0</td>
	  </tr>
	  <tr>
		<th>یحیی اورک</th>
		<td></td>
		<td></td>
		<td>5.0</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	  </tr>
	</tbody>
  </table>
